// <auto-generated />
using System;
using Day01.DbMigrations.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day01.DbMigrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404145332_V02")]
    partial class V02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day01.DbMigrations.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptName = "IT"
                        },
                        new
                        {
                            Id = 2,
                            DeptName = "HR"
                        },
                        new
                        {
                            Id = 3,
                            DeptName = "SD"
                        },
                        new
                        {
                            Id = 4,
                            DeptName = "UI"
                        },
                        new
                        {
                            Id = 5,
                            DeptName = "UX"
                        });
                });

            modelBuilder.Entity("Day01.DbMigrations.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("HRCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            DepartmentId = 1,
                            HRCode = 0,
                            Name = "John Doe",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            DepartmentId = 2,
                            HRCode = 0,
                            Name = "Jane Smith",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            DepartmentId = 3,
                            HRCode = 0,
                            Name = "Bob Johnson",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            DepartmentId = 4,
                            HRCode = 0,
                            Name = "Alice Brown",
                            Salary = 48000m
                        },
                        new
                        {
                            Id = 5,
                            Age = 32,
                            DepartmentId = 5,
                            HRCode = 0,
                            Name = "Charlie Davis",
                            Salary = 52000m
                        });
                });

            modelBuilder.Entity("Day01.DbMigrations.Models.TestGuid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestGuids");
                });

            modelBuilder.Entity("Day01.DbMigrations.Models.Employee", b =>
                {
                    b.HasOne("Day01.DbMigrations.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Day01.DbMigrations.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
