// <auto-generated />
using Day02.OneToOnePP.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day02.OneToOnePP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405072241_V01")]
    partial class V01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day02.OneToOnePP.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.Instuctor_Car", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "CarId");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.HasIndex("InstructorId")
                        .IsUnique();

                    b.ToTable("Instuctor_Cars");
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.Instuctor_Car", b =>
                {
                    b.HasOne("Day02.OneToOnePP.Models.Car", "Car")
                        .WithOne("Instuctor_Car")
                        .HasForeignKey("Day02.OneToOnePP.Models.Instuctor_Car", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Day02.OneToOnePP.Models.Instructor", "Instructor")
                        .WithOne("Instuctor_Car")
                        .HasForeignKey("Day02.OneToOnePP.Models.Instuctor_Car", "InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.Car", b =>
                {
                    b.Navigation("Instuctor_Car");
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.Instructor", b =>
                {
                    b.Navigation("Instuctor_Car");
                });
#pragma warning restore 612, 618
        }
    }
}
